apiVersion: v1
kind: Service
metadata:
  name: {{ include "authorizer.fullname" . }}
  labels:
    {{- include "authorizer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: None
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "authorizer.selectorLabels" . | nindent 4 }}

